Utility card
SoftRyzen-internship/molchanov-pchychoterapist pull request #16
Opened 2024-08-14 17:30 UTC by Marynryn

2024-08-15 08:49 UTC, bonny-art requested changes

2024-08-15 08:49 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +interface UtilityCardProps {
Перероби на тайп та винеси в окремий файл

2024-08-15 08:49 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +const UtilityCard = ({ url, text, alt }: UtilityCardProps) => {
Створи для компонента окрему папку, там розташуй файл компоненту та файл типів для пропсів types.ts

2024-08-15 08:49 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +      <Image
на десктопі та таблеті - одне зображення, на мобілці - інше. і щось треба доробити з позиціонуванням зображення.
![image](https://github.com/user-attachments/assets/fd72e0e7-6285-40a7-bc44-29a6226bec0b)

2024-08-15 08:49 UTC, bonny-art commented on src/data/target-audience/utility-card-data.json
> +    "alt": "A couple standing close together, the woman hugging herself"
Перероби українською

2024-08-15 10:39 UTC, Marynryn commented on src/components/common/utility-card.tsx
> +interface UtilityCardProps {
Зробила

2024-08-15 10:40 UTC, Marynryn commented on src/components/common/utility-card.tsx
> +const UtilityCard = ({ url, text, alt }: UtilityCardProps) => {
Зробила

2024-08-15 10:41 UTC, Marynryn commented on src/components/common/utility-card.tsx
> +      <Image
Викачала фото для усіх пристроїв, та зробила рендер по умові. через хук react-responsive.

2024-08-15 10:41 UTC, Marynryn commented on src/data/target-audience/utility-card-data.json
> +    "alt": "A couple standing close together, the woman hugging herself"
Переробила

2024-08-15 10:57 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +      <Image
![image](https://github.com/user-attachments/assets/d2d76c59-272d-4253-8cd7-fb21b4863cce)
мобайл має полоску знизу.

2024-08-15 10:59 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +      <Image
![image](https://github.com/user-attachments/assets/6e116367-4e07-4a44-9d5c-2e51cdeb1543)
таблет неякісне зображення. особливо видно, коли 1х

2024-08-15 11:00 UTC, bonny-art commented on src/components/common/utility-card.tsx
> +      <Image
з десктопом - те саме. щось ти не правильні медіаправила задала

2024-08-15 11:03 UTC, bonny-art requested changes
ще треба поправити зображення
додала там в продовження коментів

2024-08-16 07:55 UTC, bonny-art approved these changes

2024-08-16 07:55 UTC, merged